name: Feature Request
description: Propose a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you've considered
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Reasoning Quality
        - Setup / Onboarding
        - UI / UX
        - Agent Swarm
        - Evaluation
        - Documentation
        - Other
    validations:
      required: true
